import React, { Fragment } from 'react';
import { Layout, Icon } from 'antd';
import GlobalFooter from '@/components/GlobalFooter';
import { formatMessage, FormattedMessage } from 'umi/locale';

const { Footer } = Layout;

const H3CIcon = Icon.createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_1038824_1emu9nzteuv.js', // generated by iconfont.cn
});

const copyright = (
  <Fragment>
    Copyright <Icon type="copyright" /> <FormattedMessage id="layout.user.copyright.com" />
  </Fragment>
);

const FooterView = () => (
  <Footer style={{ padding: 0 }}>
    <GlobalFooter
      links={[
        {
          key: formatMessage({id:'layout.user.footer.link.main'}),
          title: formatMessage({id:'layout.user.footer.link.main'}),
          href: '/',
          blankTarget: true,
        },
        {
          key: 'H3C',
          title: <H3CIcon type="icon-h3c" />,
          href: 'http://www.h3c.com',
          blankTarget: true,
        },
        // {
        //   key: 'Ant Design',
        //   title: 'Ant Design',
        //   href: 'https://ant.design',
        //   blankTarget: true,
        // },
      ]}
      copyright={copyright}
    />
  </Footer>
);
export default FooterView;
